version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.production
    image: pech3nyka/devops-for-developers-project-74:latest
    environment:
      - NODE_ENV=production
      